<Project>

  <PropertyGroup>
    <Version>0.1.0</Version>
    <Authors>Ronald van Helden</Authors>
    <Company>TerminalNinja</Company>
    <Copyright>Copyright (c) Ronald van Helden</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/rvhelden/TerminalNinja</PackageProjectUrl>
    <RepositoryUrl>https://github.com/rvhelden/TerminalNinja.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

</Project>
