<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TerminalNinja.Xaml\TerminalNinja.Xaml.csproj" />
    <ProjectReference Include="..\TerminalNinja.Core\TerminalNinja.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.12.93" />
  </ItemGroup>

</Project>
