<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnableMicrosoftTestingPlatform>true</EnableMicrosoftTestingPlatform>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute" Version="5.3.0" />
        <PackageReference Include="TUnit" Version="1.12.93" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TerminalNinja.Core\TerminalNinja.Core.csproj" />
    </ItemGroup>

</Project>
