<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <PublishAot>true</PublishAot>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TerminalNinja\TerminalNinja.csproj" />
      <ProjectReference Include="..\TerminalNinja.Generators\TerminalNinja.Generators.csproj"
                        OutputItemType="Analyzer"
                        ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="DemoLayout.xaml">
        <LogicalName>Sample.DemoLayout.xaml</LogicalName>
      </EmbeddedResource>
      <EmbeddedResource Include="ActivityLogControl.xaml">
        <LogicalName>Sample.ActivityLogControl.xaml</LogicalName>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="ActivityLogControl.xaml" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="ActivityLogControl.cs">
        <DependentUpon>ActivityLogControl.xaml</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
