<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>13</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TerminalNinja\TerminalNinja.csproj" />
    <ProjectReference Include="..\TerminalNinja.Skia\TerminalNinja.Skia.csproj" />
    <ProjectReference Include="..\TerminalNinja.Terminal\TerminalNinja.Terminal.csproj" />
    <ProjectReference Include="..\TerminalNinja.Generators\TerminalNinja.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="TUnit" Version="1.20.0" />
  </ItemGroup>

</Project>
